# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Production Server Deployment

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run SSH command
        uses: garygrossgarten/github-action-ssh@v0.5.0
        with:
          command: cd repos/IssueTracker-13 && git pull && npm run build && npm start
          host: ${{ secrets.PROD_HOST }}
          username: junsu
          privateKey: $${{ secrets.PROD_PRIVATE_KEY }}
